telegram:
  client:
    id: api_id
    hash: api_hash
    name: "tel2gsheet"
  chats:
    expenses:
      id: expenses_chat_id
    calories:
      id: calories_chat_id
google:
  sheets:
    expenses:
      id: expenses_sheet_id
    calories:
      id: calories_chat_id
